In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Anil\Projects\CricketScorePredictor-master\data\ipl.csv')

In [10]:
df.tail()

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,129
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,129
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,129
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,129
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,129

# Reading file in Pandas

In [ ]:

df = pd.read_csv("file_path")
df = pd.read_xlsx("file_path")
df = pd.read_sql_query("query",con)
df = pd.read_json("file_path")

postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'
.format(username=POSTGRES_USERNAME,
password=POSTGRES_PASSWORD,
ipaddress=POSTGRES_ADDRESS,
port=POSTGRES_PORT,
dbname=POSTGRES_DBNAME))
# Create the connection
cnx = create_engine(postgres_str)

df = pd.read_sql_query("SELECT * FROM my_view", con=cnx))

In [13]:
print("Anil")

Anil

In [14]:
a = "Anil"

In [18]:
age = 26

In [15]:
print(a)

Anil

In [21]:
place = "Mumbai"

# Random print functions

In [22]:
print("The name of the employee is {} and his age is {} and his place of residence is {}".format(a,age,place))

The name of the employee is Anil and his age is 26 and his place of residence is Mumbai

In [24]:
print(f"The name of the employee is {a} and his age is {age} and his place of residence is {place}")

The name of the employee is Anil and his age is 26 and his place of residence is Mumbai

In [7]:
df.head(10)

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
5,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.5,2,0,0,0,222
6,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,3,0,0.6,3,0,0,0,222
7,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,3,0,1.1,3,0,0,0,222
8,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,7,0,1.2,7,0,4,0,222
9,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,11,0,1.3,11,0,8,0,222

# Create a Dataframe using Dictionary

In [8]:
df_temp = pd.DataFrame(
{
    "Name" : ['Anil','Vivek','shubham','Sumeet'],
    "Age" : [20,21,22,23],
    "Gender" : ["M","M","M","M"]    
}
)

In [9]:
df_temp

      Name  Age Gender
0     Anil   20      M
1    Vivek   21      M
2  shubham   22      M
3   Sumeet   23      M

In [36]:
dir(df_temp)

['Age',
 'Gender',
 'Name',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [38]:
df.head()

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222

In [39]:
df.tail()

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,129
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,129
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,129
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,129
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,129

In [12]:
df.shape

(76014, 15)

In [20]:
df2 = df[1000:1200].reset_index()

In [21]:
df2

,index,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1000,9,2008-04-24,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,A Symonds,SR Watson,33,2,3.1,33,2,9,1,214
1,1001,9,2008-04-24,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,VVS Laxman,SR Watson,33,2,3.2,33,2,9,1,214
2,1002,9,2008-04-24,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,VVS Laxman,SR Watson,33,2,3.3,33,2,9,1,214
3,1003,9,2008-04-24,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,VVS Laxman,SR Watson,33,2,3.4,33,2,9,1,214
4,1004,9,2008-04-24,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,VVS Laxman,SR Watson,33,2,3.5,33,2,9,1,214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1195,10,2008-04-25,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,KC Sangakkara,MA Khote,127,4,14.2,38,2,73,2,182
196,1196,10,2008-04-25,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,KC Sangakkara,MA Khote,127,4,14.3,36,2,73,2,182
197,1197,10,2008-04-25,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,KC Sangakkara,MA Khote,131,4,14.4,40,2,77,2,182
198,1198,10,2008-04-25,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,KC Sangakkara,MA Khote,132,4,14.5,40,2,78,2,182
199,1199,10,2008-04-25,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,DPMD Jayawardene,MA Khote,138,4,14.6,44,2,78,8,182

In [27]:
df2[['mid','date','venue']]

     mid        date                                       venue
0      9  2008-04-24   Rajiv Gandhi International Stadium, Uppal
1      9  2008-04-24   Rajiv Gandhi International Stadium, Uppal
2      9  2008-04-24   Rajiv Gandhi International Stadium, Uppal
3      9  2008-04-24   Rajiv Gandhi International Stadium, Uppal
4      9  2008-04-24   Rajiv Gandhi International Stadium, Uppal
..   ...         ...                                         ...
195   10  2008-04-25  Punjab Cricket Association Stadium, Mohali
196   10  2008-04-25  Punjab Cricket Association Stadium, Mohali
197   10  2008-04-25  Punjab Cricket Association Stadium, Mohali
198   10  2008-04-25  Punjab Cricket Association Stadium, Mohali
199   10  2008-04-25  Punjab Cricket Association Stadium, Mohali

[200 rows x 3 columns]

In [55]:
type(a)

pandas.core.frame.DataFrame

1000     9
1001     9
1002     9
1003     9
1004     9
        ..
1195    10
1196    10
1197    10
1198    10
1199    10
Name: mid, Length: 200, dtype: int64

In [58]:
b = df2[['mid']]

In [59]:
b

      mid
1000    9
1001    9
1002    9
1003    9
1004    9
...   ...
1195   10
1196   10
1197   10
1198   10
1199   10

[200 rows x 1 columns]

In [37]:
df.shape

(76014, 15)

In [30]:
df.columns

Index(['mid', 'date', 'venue', 'bat_team', 'bowl_team', 'batsman', 'bowler',
       'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5', 'striker',
       'non-striker', 'total'],
      dtype='object')

In [32]:
type(df[['mid']]) #This is a series

pandas.core.frame.DataFrame

In [70]:
df[['mid','venue','bat_team']]

       mid                                      venue               bat_team
0        1                      M Chinnaswamy Stadium  Kolkata Knight Riders
1        1                      M Chinnaswamy Stadium  Kolkata Knight Riders
2        1                      M Chinnaswamy Stadium  Kolkata Knight Riders
3        1                      M Chinnaswamy Stadium  Kolkata Knight Riders
4        1                      M Chinnaswamy Stadium  Kolkata Knight Riders
...    ...                                        ...                    ...
76009  617  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians
76010  617  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians
76011  617  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians
76012  617  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians
76013  617  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians

[76014 rows x 3 columns]

In [68]:
df.mid

0          1
1          1
2          1
3          1
4          1
        ...
76009    617
76010    617
76011    617
76012    617
76013    617
Name: mid, Length: 76014, dtype: int64

In [71]:
df

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,129
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,129
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,129
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,129
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,129

In [73]:
df['total'].describe()

count    76014.000000
mean       160.901452
std         29.246231
min         67.000000
25%        142.000000
50%        162.000000
75%        181.000000
max        263.000000
Name: total, dtype: float64

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222

In [51]:
df[['mid','venue']][df['total'] == df.total.max()]

       mid                                      venue
0        1                      M Chinnaswamy Stadium
1        1                      M Chinnaswamy Stadium
2        1                      M Chinnaswamy Stadium
3        1                      M Chinnaswamy Stadium
4        1                      M Chinnaswamy Stadium
...    ...                                        ...
76009  617  Rajiv Gandhi International Stadium, Uppal
76010  617  Rajiv Gandhi International Stadium, Uppal
76011  617  Rajiv Gandhi International Stadium, Uppal
76012  617  Rajiv Gandhi International Stadium, Uppal
76013  617  Rajiv Gandhi International Stadium, Uppal

[76014 rows x 2 columns]

In [35]:
df[df.total == df.total.max()]

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
42229,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,CH Gayle,B Kumar,0,0,0.1,0,0,0,0,263
42230,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,CH Gayle,B Kumar,0,0,0.2,0,0,0,0,263
42231,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,CH Gayle,B Kumar,1,0,0.3,1,0,1,0,263
42232,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,TM Dilshan,B Kumar,3,0,0.4,3,0,2,1,263
42233,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,TM Dilshan,B Kumar,3,0,0.5,3,0,2,1,263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42352,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,CH Gayle,AB Dinda,260,3,19.2,74,2,174,0,263
42353,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,SS Tiwary,AB Dinda,262,3,19.3,72,2,174,2,263
42354,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,SS Tiwary,AB Dinda,262,4,19.4,66,3,174,2,263
42355,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,CH Gayle,AB Dinda,263,4,19.5,66,3,175,0,263
42356,343,2013-04-23,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,R Rampaul,AB Dinda,263,5,19.6,65,4,175,0,263

In [6]:
df_temp

263

In [52]:
df[df.total == df.total.min()]

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,263
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,263
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,263
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,263
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,263
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,263
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,263
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,263
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,263

In [53]:
df[df.total == df.total.min()]

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,263
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,263
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,263
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,263
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,263
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,263
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,263
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,263
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,263

In [57]:
df['batsman'][df.runs == 2]

2            BB McCullum
3            BB McCullum
4            BB McCullum
5            BB McCullum
494      Y Venugopal Rao
              ...
75303        LMP Simmons
75304        LMP Simmons
75649          AM Rahane
75777            CA Lynn
75893           PA Patel
Name: batsman, Length: 649, dtype: object

In [18]:
df['venue'][2000:2300]

2000          Feroz Shah Kotla
2001          Feroz Shah Kotla
2002          Feroz Shah Kotla
2003          Feroz Shah Kotla
2004          Feroz Shah Kotla
                 ...
2295    Sawai Mansingh Stadium
2296    Sawai Mansingh Stadium
2297    Sawai Mansingh Stadium
2298    Sawai Mansingh Stadium
2299    Sawai Mansingh Stadium
Name: venue, Length: 300, dtype: object

In [ ]:
1   Anil 100
2   Anil 100 
3   Anil 200
4   a     ff
5    b   jir
6    c    ror 
7    d   jfuj
8    e   kfi
9   f   ifr
10  g   rir

In [58]:
df2 = df[['mid','date','bat_team']]

In [59]:
df2.to_csv(r'C:\Anil\Projects\DS Training\temp.csv')

In [42]:
df2

       mid        date               bat_team
0        1  2008-04-18  Kolkata Knight Riders
1        1  2008-04-18  Kolkata Knight Riders
2        1  2008-04-18  Kolkata Knight Riders
3        1  2008-04-18  Kolkata Knight Riders
4        1  2008-04-18  Kolkata Knight Riders
...    ...         ...                    ...
76009  617  2017-05-21         Mumbai Indians
76010  617  2017-05-21         Mumbai Indians
76011  617  2017-05-21         Mumbai Indians
76012  617  2017-05-21         Mumbai Indians
76013  617  2017-05-21         Mumbai Indians

[76014 rows x 3 columns]

In [43]:
#group by

In [44]:
df.head()

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222

In [60]:
df2 = df.groupby('venue')

In [65]:
df[df.venue=="Dr DY Patil Sports Academy"]

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
1482,13,2008-04-27,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,L Ronchi,RP Singh,0,0,0.1,0,0,0,0,263
1483,13,2008-04-27,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,L Ronchi,RP Singh,4,0,0.2,4,0,4,0,263
1484,13,2008-04-27,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,L Ronchi,RP Singh,4,0,0.3,4,0,4,0,263
1485,13,2008-04-27,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,L Ronchi,RP Singh,5,0,0.4,5,0,5,0,263
1486,13,2008-04-27,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,ST Jayasuriya,RP Singh,6,0,0.4,6,0,5,0,263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28563,231,2011-05-19,Dr DY Patil Sports Academy,Pune Warriors,Kolkata Knight Riders,Yuvraj Singh,L Balaji,113,6,19.3,33,1,24,15,263
28564,231,2011-05-19,Dr DY Patil Sports Academy,Pune Warriors,Kolkata Knight Riders,S Rana,L Balaji,116,6,19.3,35,1,17,0,263
28565,231,2011-05-19,Dr DY Patil Sports Academy,Pune Warriors,Kolkata Knight Riders,S Rana,L Balaji,117,6,19.4,36,1,18,0,263
28566,231,2011-05-19,Dr DY Patil Sports Academy,Pune Warriors,Kolkata Knight Riders,WD Parnell,L Balaji,118,6,19.5,37,1,18,1,263
28567,231,2011-05-19,Dr DY Patil Sports Academy,Pune Warriors,Kolkata Knight Riders,S Rana,L Balaji,118,7,19.6,36,2,18,1,263

In [66]:
for i,j in df2:
    print(i)
    print(j)
    df2.get_group(i)

Barabati Stadium
       mid        date             venue         bat_team  \
14963  122  2010-03-19  Barabati Stadium  Deccan Chargers
14964  122  2010-03-19  Barabati Stadium  Deccan Chargers
14965  122  2010-03-19  Barabati Stadium  Deccan Chargers
14966  122  2010-03-19  Barabati Stadium  Deccan Chargers
14967  122  2010-03-19  Barabati Stadium  Deccan Chargers
...    ...         ...               ...              ...
52765  428  2014-05-14  Barabati Stadium   Mumbai Indians
52766  428  2014-05-14  Barabati Stadium   Mumbai Indians
52767  428  2014-05-14  Barabati Stadium   Mumbai Indians
52768  428  2014-05-14  Barabati Stadium   Mumbai Indians
52769  428  2014-05-14  Barabati Stadium   Mumbai Indians

                   bowl_team       batsman     bowler  runs  wickets  overs  \
14963        Kings XI Punjab  AC Gilchrist  IK Pathan     1        0    0.1
14964        Kings XI Punjab    VVS Laxman  IK Pathan     1        0    0.2
14965        Kings XI Punjab    VVS Laxman  IK Pathan     2        0    0.3
14966        Kings XI Punjab  AC Gilchrist  IK Pathan     2        0    0.4
14967        Kings XI Punjab  AC Gilchrist  IK Pathan     4        0    0.5
...                      ...           ...        ...   ...      ...    ...
52765  Kolkata Knight Riders     RG Sharma  SP Narine   138        5   19.2
52766  Kolkata Knight Riders       AP Tare  SP Narine   139        5   19.3
52767  Kolkata Knight Riders    KA Pollard  SP Narine   140        5   19.4
52768  Kolkata Knight Riders       AP Tare  SP Narine   140        5   19.5
52769  Kolkata Knight Riders       AP Tare  SP Narine   141        5   19.6

       runs_last_5  wickets_last_5  striker  non-striker  total
14963            1               0        1            0    263
14964            1               0        1            0    263
14965            2               0        1            1    263
14966            2               0        1            1    263
14967            4               0        3            1    263
...            ...             ...      ...          ...    ...
52765           43               2       51            9    263
52766           41               2        9            1    263
52767           41               2       10            1    263
52768           41               2       10            1    263
52769           42               2       10            2    263

[856 rows x 15 columns]
Brabourne Stadium
       mid        date              venue          bat_team  \
13704  112  2010-03-13  Brabourne Stadium    Mumbai Indians
13705  112  2010-03-13  Brabourne Stadium    Mumbai Indians
13706  112  2010-03-13  Brabourne Stadium    Mumbai Indians
13707  112  2010-03-13  Brabourne Stadium    Mumbai Indians
13708  112  2010-03-13  Brabourne Stadium    Mumbai Indians
...    ...         ...                ...               ...
61311  498  2015-05-16  Brabourne Stadium  Rajasthan Royals
61312  498  2015-05-16  Brabourne Stadium  Rajasthan Royals
61313  498  2015-05-16  Brabourne Stadium  Rajasthan Royals
61314  498  2015-05-16  Brabourne Stadium  Rajasthan Royals
61315  498  2015-05-16  Brabourne Stadium  Rajasthan Royals

                   bowl_team        batsman          bowler  runs  wickets  \
13704       Rajasthan Royals  ST Jayasuriya  AD Mascarenhas     4        0
13705       Rajasthan Royals  ST Jayasuriya  AD Mascarenhas     4        0
13706       Rajasthan Royals  ST Jayasuriya  AD Mascarenhas     8        0
13707       Rajasthan Royals  ST Jayasuriya  AD Mascarenhas     8        0
13708       Rajasthan Royals  ST Jayasuriya  AD Mascarenhas    12        0
...                      ...            ...             ...   ...      ...
61311  Kolkata Knight Riders      SR Watson        UT Yadav   196        5
61312  Kolkata Knight Riders      CH Morris        UT Yadav   197        5
61313  Kolkata Knight Riders      SR Watson        UT Yadav   198        5
61314  Kolkata Knight Riders      CH Morris        UT Yadav   198        5
61315  Kolkata Knight Riders      CH Morris        UT Yadav   199        6

       overs  runs_last_5  wickets_last_5  striker  non-striker  total
13704    0.1            4               0        4            0    263
13705    0.2            4               0        4            0    263
13706    0.3            8               0        8            0    263
13707    0.4            8               0        8            0    263
13708    0.5           12               0       12            0    263
...      ...          ...             ...      ...          ...    ...
61311   19.2           55               1      103            2    263
61312   19.3           52               1      103            3    263
61313   19.4           52               1      104            3    263
61314   19.5           51               1      104            3    263
61315   19.6           50               2      104            4    263

[1380 rows x 15 columns]
Buffalo Park
       mid        date         venue        bat_team              bowl_team  \
9092    75  2009-05-01  Buffalo Park  Mumbai Indians  Kolkata Knight Riders
9093    75  2009-05-01  Buffalo Park  Mumbai Indians  Kolkata Knight Riders
9094    75  2009-05-01  Buffalo Park  Mumbai Indians  Kolkata Knight Riders
9095    75  2009-05-01  Buffalo Park  Mumbai Indians  Kolkata Knight Riders
9096    75  2009-05-01  Buffalo Park  Mumbai Indians  Kolkata Knight Riders
...    ...         ...           ...             ...                    ...
10582   86  2009-05-08  Buffalo Park  Mumbai Indians       Delhi Daredevils
10583   86  2009-05-08  Buffalo Park  Mumbai Indians       Delhi Daredevils
10584   86  2009-05-08  Buffalo Park  Mumbai Indians       Delhi Daredevils
10585   86  2009-05-08  Buffalo Park  Mumbai Indians       Delhi Daredevils
10586   86  2009-05-08  Buffalo Park  Mumbai Indians       Delhi Daredevils

             batsman    bowler  runs  wickets  overs  runs_last_5  \
9092   ST Jayasuriya  I Sharma     1        0    0.0            1
9093   ST Jayasuriya  I Sharma     2        0    0.1            2
9094    SR Tendulkar  I Sharma     3        0    0.1            3
9095    SR Tendulkar  I Sharma     3        0    0.2            3
9096    SR Tendulkar  I Sharma     5        0    0.3            5
...              ...       ...   ...      ...    ...          ...
10582    DS Kulkarni  R Bhatia   114        8   19.2           41
10583    DS Kulkarni  R Bhatia   115        8   19.3           42
10584      AM Rahane  R Bhatia   115        9   19.4           41
10585    DS Kulkarni  R Bhatia   115        9   19.5           37
10586    DS Kulkarni  R Bhatia   116       10   19.6           37

       wickets_last_5  striker  non-striker  total
9092                0        0            0    263
9093                0        1            0    263
9094                0        1            0    263
9095                0        1            0    263
9096                0        2            1    263
...               ...      ...          ...    ...
10582               4       12            0    263
10583               4       12            0    263
10584               5       12            0    263
10585               5        0            0    263
10586               6        1            0    263

[380 rows x 15 columns]
De Beers Diamond Oval
       mid        date                  venue         bat_team  \
10587   87  2009-05-09  De Beers Diamond Oval  Deccan Chargers
10588   87  2009-05-09  De Beers Diamond Oval  Deccan Chargers
10589   87  2009-05-09  De Beers Diamond Oval  Deccan Chargers
10590   87  2009-05-09  De Beers Diamond Oval  Deccan Chargers
10591   87  2009-05-09  De Beers Diamond Oval  Deccan Chargers
...    ...         ...                    ...              ...
11203   91  2009-05-11  De Beers Diamond Oval  Deccan Chargers
11204   91  2009-05-11  De Beers Diamond Oval  Deccan Chargers
11205   91  2009-05-11  De Beers Diamond Oval  Deccan Chargers
11206   91  2009-05-11  De Beers Diamond Oval  Deccan Chargers
11207   91  2009-05-11  De Beers Diamond Oval  Deccan Chargers

              bowl_team       batsman     bowler  runs  wickets  overs  \
10587   Kings XI Punjab  AC Gilchrist      B Lee     0        0    0.1
10588   Kings XI Punjab  AC Gilchrist      B Lee     0        0    0.2
10589   Kings XI Punjab  AC Gilchrist      B Lee     0        0    0.3
10590   Kings XI Punjab  AC Gilchrist      B Lee     1        0    0.3
10591   Kings XI Punjab  AC Gilchrist      B Lee     5        0    0.4
...                 ...           ...        ...   ...      ...    ...
11203  Rajasthan Royals      DR Smith  YK Pathan   159        6   19.2
11204  Rajasthan Royals  DB Ravi Teja  YK Pathan   163        6   19.3
11205  Rajasthan Royals  DB Ravi Teja  YK Pathan   164        6   19.4
11206  Rajasthan Royals      DR Smith  YK Pathan   164        7   19.5
11207  Rajasthan Royals  DB Ravi Teja  YK Pathan   166        7   19.6

       runs_last_5  wickets_last_5  striker  non-striker  total
10587            0               0        0            0    263
10588            0               0        0            0    263
10589            0               0        0            0    263
10590            1               0        0            0    263
10591            5               0        4            0    263
...            ...             ...      ...          ...    ...
11203           57               2       47            0    263
11204           59               2       47            4    263
11205           59               2       47            5    263
11206           58               3       47            5    263
11207           58               3        7            0    263

[368 rows x 15 columns]
Dr DY Patil Sports Academy
       mid        date                       venue        bat_team  \
1482    13  2008-04-27  Dr DY Patil Sports Academy  Mumbai Indians
1483    13  2008-04-27  Dr DY Patil Sports Academy  Mumbai Indians
1484    13  2008-04-27  Dr DY Patil Sports Academy  Mumbai Indians
1485    13  2008-04-27  Dr DY Patil Sports Academy  Mumbai Indians
1486    13  2008-04-27  Dr DY Patil Sports Academy  Mumbai Indians
...    ...         ...                         ...             ...
28563  231  2011-05-19  Dr DY Patil Sports Academy   Pune Warriors
28564  231  2011-05-19  Dr DY Patil Sports Academy   Pune Warriors
28565  231  2011-05-19  Dr DY Patil Sports Academy   Pune Warriors
28566  231  2011-05-19  Dr DY Patil Sports Academy   Pune Warriors
28567  231  2011-05-19  Dr DY Patil Sports Academy   Pune Warriors

                   bowl_team        batsman    bowler  runs  wickets  overs  \
1482         Deccan Chargers       L Ronchi  RP Singh     0        0    0.1
1483         Deccan Chargers       L Ronchi  RP Singh     4        0    0.2
1484         Deccan Chargers       L Ronchi  RP Singh     4        0    0.3
1485         Deccan Chargers       L Ronchi  RP Singh     5        0    0.4
1486         Deccan Chargers  ST Jayasuriya  RP Singh     6        0    0.4
...                      ...            ...       ...   ...      ...    ...
28563  Kolkata Knight Riders   Yuvraj Singh  L Balaji   113        6   19.3
28564  Kolkata Knight Riders         S Rana  L Balaji   116        6   19.3
28565  Kolkata Knight Riders         S Rana  L Balaji   117        6   19.4
28566  Kolkata Knight Riders     WD Parnell  L Balaji   118        6   19.5
28567  Kolkata Knight Riders         S Rana  L Balaji   118        7   19.6

       runs_last_5  wickets_last_5  striker  non-striker  total
1482             0               0        0            0    263
1483             4               0        4            0    263
1484             4               0        4            0    263
1485             5               0        5            0    263
1486             6               0        5            0    263
...            ...             ...      ...          ...    ...
28563           33               1       24           15    263
28564           35               1       17            0    263
28565           36               1       18            0    263
28566           37               1       18            1    263
28567           36               2       18            1    263

[2088 rows x 15 columns]
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium
       mid        date                                              venue  \
30133  245  2012-04-07  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
30134  245  2012-04-07  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
30135  245  2012-04-07  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
30136  245  2012-04-07  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
30137  245  2012-04-07  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
...    ...         ...                                                ...
67984  552  2016-05-21  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
67985  552  2016-05-21  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
67986  552  2016-05-21  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
67987  552  2016-05-21  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
67988  552  2016-05-21  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...

                  bat_team                bowl_team    batsman        bowler  \
30133  Chennai Super Kings          Deccan Chargers    M Vijay  Ankit Sharma
30134  Chennai Super Kings          Deccan Chargers    M Vijay  Ankit Sharma
30135  Chennai Super Kings          Deccan Chargers    M Vijay  Ankit Sharma
30136  Chennai Super Kings          Deccan Chargers    M Vijay  Ankit Sharma
30137  Chennai Super Kings          Deccan Chargers    M Vijay  Ankit Sharma
...                    ...                      ...        ...           ...
67984      Kings XI Punjab  Rising Pune Supergiants   R Dhawan   NLTC Perera
67985      Kings XI Punjab  Rising Pune Supergiants   R Dhawan   NLTC Perera
67986      Kings XI Punjab  Rising Pune Supergiants  KJ Abbott   NLTC Perera
67987      Kings XI Punjab  Rising Pune Supergiants   R Dhawan   NLTC Perera
67988      Kings XI Punjab  Rising Pune Supergiants   R Dhawan   NLTC Perera

       runs  wickets  overs  runs_last_5  wickets_last_5  striker  \
30133     2        0    0.1            2               0        2
30134     2        0    0.2            2               0        2
30135     2        0    0.3            2               0        2
30136     2        0    0.4            2               0        2
30137     2        1    0.5            2               1        2
...     ...      ...    ...          ...             ...      ...
67984   166        7   19.2           53               5        6
67985   167        7   19.3           54               5        7
67986   168        7   19.4           54               5        7
67987   170        7   19.5           50               5        9
67988   172        7   19.6           52               5       11

       non-striker  total
30133            0    263
30134            0    263
30135            0    263
30136            0    263
30137            0    263
...            ...    ...
67984            0    263
67985            0    263
67986            1    263
67987            1    263
67988            1    263

[1113 rows x 15 columns]
Dubai International Cricket Stadium
       mid        date                                venue  \
48476  394  2014-04-19  Dubai International Cricket Stadium
48477  394  2014-04-19  Dubai International Cricket Stadium
48478  394  2014-04-19  Dubai International Cricket Stadium
48479  394  2014-04-19  Dubai International Cricket Stadium
48480  394  2014-04-19  Dubai International Cricket Stadium
...    ...         ...                                  ...
50416  409  2014-04-30  Dubai International Cricket Stadium
50417  409  2014-04-30  Dubai International Cricket Stadium
50418  409  2014-04-30  Dubai International Cricket Stadium
50419  409  2014-04-30  Dubai International Cricket Stadium
50420  409  2014-04-30  Dubai International Cricket Stadium

                  bat_team                    bowl_team     batsman  \
48476       Mumbai Indians  Royal Challengers Bangalore  MEK Hussey
48477       Mumbai Indians  Royal Challengers Bangalore     AP Tare
48478       Mumbai Indians  Royal Challengers Bangalore  MEK Hussey
48479       Mumbai Indians  Royal Challengers Bangalore  MEK Hussey
48480       Mumbai Indians  Royal Challengers Bangalore  MEK Hussey
...                    ...                          ...         ...
50416  Sunrisers Hyderabad               Mumbai Indians    KL Rahul
50417  Sunrisers Hyderabad               Mumbai Indians     NV Ojha
50418  Sunrisers Hyderabad               Mumbai Indians   IK Pathan
50419  Sunrisers Hyderabad               Mumbai Indians     NV Ojha
50420  Sunrisers Hyderabad               Mumbai Indians     NV Ojha

           bowler  runs  wickets  overs  runs_last_5  wickets_last_5  striker  \
48476    MA Starc     1        0    0.1            1               0        1
48477    MA Starc     2        0    0.2            2               0        1
48478    MA Starc     4        0    0.3            4               0        3
48479    MA Starc     4        0    0.4            4               0        3
48480    MA Starc     8        0    0.5            8               0        7
...           ...   ...      ...    ...          ...             ...      ...
50416  SL Malinga   162        5   19.2           47               3       46
50417  SL Malinga   163        5   19.3           46               3        2
50418  SL Malinga   164        5   19.4           46               3        2
50419  SL Malinga   168        5   19.5           49               3        6
50420  SL Malinga   172        5   19.6           52               3       10

       non-striker  total
48476            0    263
48477            1    263
48478            1    263
48479            1    263
48480            1    263
...            ...    ...
50416            1    263
50417            0    263
50418            1    263
50419            1    263
50420            1    263

[868 rows x 15 columns]
Eden Gardens
       mid        date         venue         bat_team              bowl_team  \
493      5  2008-04-20  Eden Gardens  Deccan Chargers  Kolkata Knight Riders
494      5  2008-04-20  Eden Gardens  Deccan Chargers  Kolkata Knight Riders
495      5  2008-04-20  Eden Gardens  Deccan Chargers  Kolkata Knight Riders
496      5  2008-04-20  Eden Gardens  Deccan Chargers  Kolkata Knight Riders
497      5  2008-04-20  Eden Gardens  Deccan Chargers  Kolkata Knight Riders
...    ...         ...           ...              ...                    ...
75418  612  2017-05-13  Eden Gardens   Mumbai Indians  Kolkata Knight Riders
75419  612  2017-05-13  Eden Gardens   Mumbai Indians  Kolkata Knight Riders
75420  612  2017-05-13  Eden Gardens   Mumbai Indians  Kolkata Knight Riders
75421  612  2017-05-13  Eden Gardens   Mumbai Indians  Kolkata Knight Riders
75422  612  2017-05-13  Eden Gardens   Mumbai Indians  Kolkata Knight Riders

               batsman    bowler  runs  wickets  overs  runs_last_5  \
493       AC Gilchrist  AB Dinda     1        0    0.1            1
494    Y Venugopal Rao  AB Dinda     2        0    0.1            2
495    Y Venugopal Rao  AB Dinda     4        0    0.2            4
496    Y Venugopal Rao  AB Dinda     4        0    0.3            4
497    Y Venugopal Rao  AB Dinda     4        0    0.4            4
...                ...       ...   ...      ...    ...          ...
75418       KA Pollard  TA Boult   170        4   19.3           61
75419       KA Pollard  TA Boult   170        5   19.4           60
75420        HH Pandya  TA Boult   171        5   19.4           57
75421        HH Pandya  TA Boult   172        5   19.5           54
75422        KH Pandya  TA Boult   173        5   19.6           54

       wickets_last_5  striker  non-striker  total

       mid        date      venue             bat_team            bowl_team  \
7475    62  2009-04-23  Kingsmead     Delhi Daredevils  Chennai Super Kings
7476    62  2009-04-23  Kingsmead     Delhi Daredevils  Chennai Super Kings
7477    62  2009-04-23  Kingsmead     Delhi Daredevils  Chennai Super Kings
7478    62  2009-04-23  Kingsmead     Delhi Daredevils  Chennai Super Kings
7479    62  2009-04-23  Kingsmead     Delhi Daredevils  Chennai Super Kings
...    ...         ...        ...                  ...                  ...
12946  105  2009-05-20  Kingsmead  Chennai Super Kings      Kings XI Punjab
12947  105  2009-05-20  Kingsmead  Chennai Super Kings      Kings XI Punjab
12948  105  2009-05-20  Kingsmead  Chennai Super Kings      Kings XI Punjab
12949  105  2009-05-20  Kingsmead  Chennai Super Kings      Kings XI Punjab
12950  105  2009-05-20  Kingsmead  Chennai Super Kings      Kings XI Punjab

              batsman     bowler  runs  wickets  overs  runs_last_5  \
7475        G Gambhir   L Balaji     0        1    0.1            0
7476   AB de Villiers   L Balaji     1        1    0.2            1
7477         V Sehwag   L Balaji     1        1    0.3            1
7478         V Sehwag   L Balaji     1        1    0.4            1
7479         V Sehwag   L Balaji     1        1    0.5            1
...               ...        ...   ...      ...    ...          ...
12946        L Balaji  IK Pathan   112        8   19.2           16
12947        L Balaji  IK Pathan   113        8   19.3           17
12948      T Thushara  IK Pathan   114        9   19.4           18
12949  M Muralitharan  IK Pathan   115        9   19.5           19
12950        L Balaji  IK Pathan   116        9   19.6           19

       wickets_last_5  striker  non-striker  total
7475                1        0            0    263
7476                1        1            0    263
7477                1        1            0    263
7478                1        1            0    263
7479                1        1            0    263
...               ...      ...          ...    ...
12946               3        1            0    263
12947               2        2            0    263
12948               3        2            1    263
12949               3        2            1    263
12950               3        2            1    263

[1731 rows x 15 columns]
M Chinnaswamy Stadium
       mid        date                  venue               bat_team  \
0        1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
1        1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
2        1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
3        1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
4        1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
...    ...         ...                    ...                    ...
75884  616  2017-05-19  M Chinnaswamy Stadium  Kolkata Knight Riders
75885  616  2017-05-19  M Chinnaswamy Stadium  Kolkata Knight Riders
75886  616  2017-05-19  M Chinnaswamy Stadium  Kolkata Knight Riders
75887  616  2017-05-19  M Chinnaswamy Stadium  Kolkata Knight Riders
75888  616  2017-05-19  M Chinnaswamy Stadium  Kolkata Knight Riders

                         bowl_team      batsman      bowler  runs  wickets  \
0      Royal Challengers Bangalore   SC Ganguly     P Kumar     1        0
1      Royal Challengers Bangalore  BB McCullum     P Kumar     1        0
2      Royal Challengers Bangalore  BB McCullum     P Kumar     2        0
3      Royal Challengers Bangalore  BB McCullum     P Kumar     2        0
4      Royal Challengers Bangalore  BB McCullum     P Kumar     2        0
...                            ...          ...         ...   ...      ...
75884               Mumbai Indians     UT Yadav  SL Malinga   106        9
75885               Mumbai Indians     UT Yadav  SL Malinga   107        9
75886               Mumbai Indians   AS Rajpoot  SL Malinga   107        9
75887               Mumbai Indians   AS Rajpoot  SL Malinga   107        9
75888               Mumbai Indians   AS Rajpoot  SL Malinga   107       10

       overs  runs_last_5  wickets_last_5  striker  non-striker  total
0        0.1            1               0        0            0    263
1        0.2            1               0        0            0    263
2        0.2            2               0        0            0    263
3        0.3            2               0        0            0    263
4        0.4            2               0        0            0    263
...      ...          ...             ...      ...          ...    ...
75884   18.1           29               4        4            1    263
75885   18.2           29               4        4            2    263
75886   18.3           28               4        4            2    263
75887   18.4           24               4        4            2    263
75888   18.5           23               5        4            2    263

[7443 rows x 15 columns]
MA Chidambaram Stadium, Chepauk
       mid        date                            venue             bat_team  \
855      8  2008-04-23  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
856      8  2008-04-23  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
857      8  2008-04-23  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
858      8  2008-04-23  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
859      8  2008-04-23  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
...    ...         ...                              ...                  ...
60627  492  2015-05-10  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
60628  492  2015-05-10  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
60629  492  2015-05-10  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
60630  492  2015-05-10  MA Chidambaram Stadium, Chepauk  Chennai Super Kings
60631  492  2015-05-10  MA Chidambaram Stadium, Chepauk  Chennai Super Kings

              bowl_team   batsman      bowler  runs  wickets  overs  \
855      Mumbai Indians  PA Patel  SM Pollock     1        0    0.0
856      Mumbai Indians  PA Patel  SM Pollock     1        0    0.1
857      Mumbai Indians  PA Patel  SM Pollock     1        0    0.2
858      Mumbai Indians  PA Patel  SM Pollock     1        0    0.3
859      Mumbai Indians  PA Patel  SM Pollock     5        0    0.4
...                 ...       ...         ...   ...      ...    ...
60627  Rajasthan Royals  DJ Bravo   CH Morris   154        5   19.2
60628  Rajasthan Royals  MS Dhoni   CH Morris   154        5   19.3
60629  Rajasthan Royals  MS Dhoni   CH Morris   155        5   19.4
60630  Rajasthan Royals  DJ Bravo   CH Morris   156        5   19.5
60631  Rajasthan Royals  MS Dhoni   CH Morris   157        5   19.6

       runs_last_5  wickets_last_5  striker  non-striker  total
855              1               0        0            0    263
856              1               0        0            0    263
857              1               0        0            0    263
858              1               0        0            0    263
859              5               0        4            0    263
...            ...             ...      ...          ...    ...
60627           50               3       14           11    263
60628           46               3       14           11    263
60629           47               3       14           12    263
60630           48               3       15           12    263
60631           49               3       15           13    263

[5972 rows x 15 columns]
Maharashtra Cricket Association Stadium
       mid        date                                    venue  \
55471  451  2015-04-10  Maharashtra Cricket Association Stadium
55472  451  2015-04-10  Maharashtra Cricket Association Stadium
55473  451  2015-04-10  Maharashtra Cricket Association Stadium
55474  451  2015-04-10  Maharashtra Cricket Association Stadium
55475  451  2015-04-10  Maharashtra Cricket Association Stadium
...    ...         ...                                      ...
75516  613  2017-05-14  Maharashtra Cricket Association Stadium
75517  613  2017-05-14  Maharashtra Cricket Association Stadium
75518  613  2017-05-14  Maharashtra Cricket Association Stadium
75519  613  2017-05-14  Maharashtra Cricket Association Stadium
75520  613  2017-05-14  Maharashtra Cricket Association Stadium

               bat_team               bowl_team    batsman          bowler  \
55471  Rajasthan Royals         Kings XI Punjab  AM Rahane  Sandeep Sharma
55472  Rajasthan Royals         Kings XI Punjab  AM Rahane  Sandeep Sharma
55473  Rajasthan Royals         Kings XI Punjab  AM Rahane  Sandeep Sharma
55474  Rajasthan Royals         Kings XI Punjab  AM Rahane  Sandeep Sharma
55475  Rajasthan Royals         Kings XI Punjab  AM Rahane  Sandeep Sharma
...                 ...                     ...        ...             ...
75516   Kings XI Punjab  Rising Pune Supergiant   I Sharma         A Zampa
75517   Kings XI Punjab  Rising Pune Supergiant  MM Sharma         A Zampa
75518   Kings XI Punjab  Rising Pune Supergiant  MM Sharma         A Zampa
75519   Kings XI Punjab  Rising Pune Supergiant  MM Sharma         A Zampa
75520   Kings XI Punjab  Rising Pune Supergiant  MM Sharma         A Zampa

       runs  wickets  overs  runs_last_5  wickets_last_5  striker  \
55471     4        0    0.1            4               0        0
55472     4        0    0.2            4               0        0
55473     4        0    0.3            4               0        0
55474     4        0    0.4            4               0        0
55475     4        0    0.5            4               0        0
...     ...      ...    ...          ...             ...      ...
75516    71        9   15.1           15               3        4
75517    73        9   15.2           16               3        6
75518    73        9   15.3           15               3        6
75519    73        9   15.4           15               3        6
75520    73       10   15.5           15               4        6

       non-striker  total
55471            0    263
55472            0    263
55473            0    263
55474            0    263
55475            0    263
...            ...    ...
75516            1    263
75517            0    263
75518            0    263
75519            0    263
75520            0    263

[1843 rows x 15 columns]
Nehru Stadium
       mid        date          venue              bat_team  \
21310  173  2011-04-09  Nehru Stadium  Kochi Tuskers Kerala
21311  173  2011-04-09  Nehru Stadium  Kochi Tuskers Kerala
21312  173  2011-04-09  Nehru Stadium  Kochi Tuskers Kerala
21313  173  2011-04-09  Nehru Stadium  Kochi Tuskers Kerala
21314  173  2011-04-09  Nehru Stadium  Kochi Tuskers Kerala
...    ...         ...            ...                   ...
26344  213  2011-05-05  Nehru Stadium  Kochi Tuskers Kerala
26345  213  2011-05-05  Nehru Stadium  Kochi Tuskers Kerala
26346  213  2011-05-05  Nehru Stadium  Kochi Tuskers Kerala
26347  213  2011-05-05  Nehru Stadium  Kochi Tuskers Kerala
26348  213  2011-05-05  Nehru Stadium  Kochi Tuskers Kerala

                         bowl_team      batsman  bowler  runs  wickets  overs  \
21310  Royal Challengers Bangalore  BB McCullum  Z Khan     1        0    0.1
21311  Royal Challengers Bangalore   VVS Laxman  Z Khan     2        0    0.2
21312  Royal Challengers Bangalore  BB McCullum  Z Khan     6        0    0.3
21313  Royal Challengers Bangalore  BB McCullum  Z Khan     6        0    0.4
21314  Royal Challengers Bangalore  BB McCullum  Z Khan     7        0    0.5
...                            ...          ...     ...   ...      ...    ...
26344        Kolkata Knight Riders     BJ Hodge   B Lee   141        5   19.2
26345        Kolkata Knight Riders     BJ Hodge   B Lee   145        5   19.3
26346        Kolkata Knight Riders     BJ Hodge   B Lee   151        5   19.4
26347        Kolkata Knight Riders     BJ Hodge   B Lee   155        5   19.5
26348        Kolkata Knight Riders     BJ Hodge   B Lee   156        5   19.6

       runs_last_5  wickets_last_5  striker  non-striker  total
21310            1               0        1            0    263
21311            2               0        1            0    263
21312            6               0        5            0    263
21313            6               0        5            0    263
21314            7               0        6            0    263
...            ...             ...      ...          ...    ...
26344           45               1       20            1    263
26345           48               1       24            1    263
26346           53               1       30            1    263
26347           56               1       34            1    263
26348           57               1       35            1    263

[499 rows x 15 columns]
New Wanderers Stadium
       mid        date                  venue             bat_team  \
9466    78  2009-05-02  New Wanderers Stadium  Chennai Super Kings
9467    78  2009-05-02  New Wanderers Stadium  Chennai Super Kings
9468    78  2009-05-02  New Wanderers Stadium  Chennai Super Kings
9469    78  2009-05-02  New Wanderers Stadium  Chennai Super Kings
9470    78  2009-05-02  New Wanderers Stadium  Chennai Super Kings
...    ...         ...                    ...                  ...
13572  110  2009-05-24  New Wanderers Stadium      Deccan Chargers
13573  110  2009-05-24  New Wanderers Stadium      Deccan Chargers
13574  110  2009-05-24  New Wanderers Stadium      Deccan Chargers
13575  110  2009-05-24  New Wanderers Stadium      Deccan Chargers
13576  110  2009-05-24  New Wanderers Stadium      Deccan Chargers

                         bowl_team    batsman         bowler  runs  wickets  \
9466              Delhi Daredevils    M Vijay      DP Nannes     1        0
9467              Delhi Daredevils    M Vijay      DP Nannes     1        0
9468              Delhi Daredevils    M Vijay      DP Nannes     2        0
9469              Delhi Daredevils  ML Hayden      DP Nannes     6        0
9470              Delhi Daredevils  ML Hayden      DP Nannes     6        0
...                            ...        ...            ...   ...      ...
13572  Royal Challengers Bangalore  RJ Harris  R Vinay Kumar   136        6
13573  Royal Challengers Bangalore  RJ Harris  R Vinay Kumar   138        6
13574  Royal Challengers Bangalore  RJ Harris  R Vinay Kumar   140        6
13575  Royal Challengers Bangalore  RJ Harris  R Vinay Kumar   142        6
13576  Royal Challengers Bangalore  RJ Harris  R Vinay Kumar   143        6

       overs  runs_last_5  wickets_last_5  striker  non-striker  total
9466     0.0            1               0        0            0    263
9467     0.1            1               0        0            0    263
9468     0.2            2               0        1            0    263
9469     0.3            6               0        4            1    263
9470     0.4            6               0        4            1    263
...      ...          ...             ...      ...          ...    ...
13572   19.2           39               3       53            2    263
13573   19.3           39               3       53            4    263
13574   19.4           40               3       53            6    263
13575   19.5           41               3       53            8    263
13576   19.6           41               3       53            9    263

[995 rows x 15 columns]
Newlands
      mid        date     venue         bat_team            bowl_team  \
6868   57  2009-04-18  Newlands   Mumbai Indians  Chennai Super Kings
6869   57  2009-04-18  Newlands   Mumbai Indians  Chennai Super Kings
6870   57  2009-04-18  Newlands   Mumbai Indians  Chennai Super Kings
6871   57  2009-04-18  Newlands   Mumbai Indians  Chennai Super Kings
6872   57  2009-04-18  Newlands   Mumbai Indians  Chennai Super Kings
...   ...         ...       ...              ...                  ...
8219   67  2009-04-26  Newlands  Kings XI Punjab     Rajasthan Royals
8220   67  2009-04-26  Newlands  Kings XI Punjab     Rajasthan Royals
8221   67  2009-04-26  Newlands  Kings XI Punjab     Rajasthan Royals
8222   67  2009-04-26  Newlands  Kings XI Punjab     Rajasthan Royals
8223   67  2009-04-26  Newlands  Kings XI Punjab     Rajasthan Royals

            batsman    bowler  runs  wickets  overs  runs_last_5  \
6868  ST Jayasuriya   MS Gony     1        0    0.1            1
6869   SR Tendulkar   MS Gony     1        0    0.2            1
6870   SR Tendulkar   MS Gony     1        0    0.3            1
6871   SR Tendulkar   MS Gony     2        0    0.4            2
6872  ST Jayasuriya   MS Gony     2        0    0.5            2
...             ...       ...   ...      ...    ...          ...
8219      PP Chawla  MM Patel   134        6   19.3           38
8220      PP Chawla  MM Patel   136        6   19.3           39
8221        WA Mota  MM Patel   136        6   19.4           39
8222        WA Mota  MM Patel   137        6   19.5           39
8223      PP Chawla  MM Patel   139        6   19.6           37

      wickets_last_5  striker  non-striker  total
6868               0        1            0    263
6869               0        1            0    263
6870               0        1            0    263
6871               0        1            1    263
6872               0        1            1    263
...              ...      ...          ...    ...
8219               2        4            0    263
8220               2        4            0    263
8221               2        4            0    263
8222               2        4            1    263
8223               2        6            1    263

[737 rows x 15 columns]
OUTsurance Oval
       mid        date            venue          bat_team         bowl_team  \
11831   97  2009-05-15  OUTsurance Oval  Delhi Daredevils   Kings XI Punjab
11832   97  2009-05-15  OUTsurance Oval  Delhi Daredevils   Kings XI Punjab
11833   97  2009-05-15  OUTsurance Oval  Delhi Daredevils   Kings XI Punjab
11834   97  2009-05-15  OUTsurance Oval  Delhi Daredevils   Kings XI Punjab
11835   97  2009-05-15  OUTsurance Oval  Delhi Daredevils   Kings XI Punjab
...    ...         ...              ...               ...               ...
12449  101  2009-05-17  OUTsurance Oval  Delhi Daredevils  Rajasthan Royals
12450  101  2009-05-17  OUTsurance Oval  Delhi Daredevils  Rajasthan Royals
12451  101  2009-05-17  OUTsurance Oval  Delhi Daredevils  Rajasthan Royals
12452  101  2009-05-17  OUTsurance Oval  Delhi Daredevils  Rajasthan Royals
12453  101  2009-05-17  OUTsurance Oval  Delhi Daredevils  Rajasthan Royals

              batsman    bowler  runs  wickets  overs  runs_last_5  \
11831       G Gambhir     B Lee     0        0    0.1            0
11832       G Gambhir     B Lee     0        0    0.2            0
11833       G Gambhir     B Lee     1        0    0.3            1
11834        V Sehwag     B Lee     5        0    0.4            5
11835        V Sehwag     B Lee     6        0    0.5            6
...               ...       ...   ...      ...    ...          ...
12449  AB de Villiers  SK Warne   142        3   19.2           50
12450      KD Karthik  SK Warne   144        3   19.3           51
12451      KD Karthik  SK Warne   146        3   19.4           52
12452      KD Karthik  SK Warne   148        3   19.5           53
12453      KD Karthik  SK Warne   150        3   19.6           55

       wickets_last_5  striker  non-striker  total
11831               0        0            0    263
11832               0        0            0    263
11833               0        1            0    263
11834               0        4            1    263
11835               0        4            1    263
...               ...      ...          ...    ...
12449               1       79           15    263
12450               1       79           17    263
12451               1       79           19    263
12452               1       79           21    263
12453               1       79           23    263

[251 rows x 15 columns]
Punjab Cricket Association IS Bindra Stadium, Mohali
       mid        date                                              venue  \
62176  506  2016-04-11  Punjab Cricket Association IS Bindra Stadium, ...
62177  506  2016-04-11  Punjab Cricket Association IS Bindra Stadium, ...
62178  506  2016-04-11  Punjab Cricket Association IS Bindra Stadium, ...
62179  506  2016-04-11  Punjab Cricket Association IS Bindra Stadium, ...
62180  506  2016-04-11  Punjab Cricket Association IS Bindra Stadium, ...
...    ...         ...                                                ...
74798  607  2017-05-09  Punjab Cricket Association IS Bindra Stadium, ...
74799  607  2017-05-09  Punjab Cricket Association IS Bindra Stadium, ...
74800  607  2017-05-09  Punjab Cricket Association IS Bindra Stadium, ...
74801  607  2017-05-09  Punjab Cricket Association IS Bindra Stadium, ...
74802  607  2017-05-09  Punjab Cricket Association IS Bindra Stadium, ...

              bat_team              bowl_team    batsman      bowler  runs  \
62176  Kings XI Punjab          Gujarat Lions    M Vijay     P Kumar     1
62177  Kings XI Punjab          Gujarat Lions    M Vohra     P Kumar     1
62178  Kings XI Punjab          Gujarat Lions    M Vohra     P Kumar     1
62179  Kings XI Punjab          Gujarat Lions    M Vohra     P Kumar     2
62180  Kings XI Punjab          Gujarat Lions    M Vijay     P Kumar     2
...                ...                    ...        ...         ...   ...
74798  Kings XI Punjab  Kolkata Knight Riders   AR Patel  AS Rajpoot   160
74799  Kings XI Punjab  Kolkata Knight Riders  R Tewatia  AS Rajpoot   161
74800  Kings XI Punjab  Kolkata Knight Riders   AR Patel  AS Rajpoot   162
74801  Kings XI Punjab  Kolkata Knight Riders  R Tewatia  AS Rajpoot   166
74802  Kings XI Punjab  Kolkata Knight Riders  R Tewatia  AS Rajpoot   167

       wickets  overs  runs_last_5  wickets_last_5  striker  non-striker  \
62176        0    0.1            1               0        1            0
62177        0    0.2            1               0        1            0
62178        0    0.3            1               0        1            0
62179        0    0.4            2               0        1            1
62180        0    0.5            2               0        1            1
...        ...    ...          ...             ...      ...          ...
74798        6   19.2           49               3       10            8
74799        6   19.3           49               3       10            8
74800        6   19.4           48               3       10            8
74801        6   19.5           51               3       14            8
74802        6   19.6           46               3       15            8

       total
62176    263
62177    263
62178    263
62179    263
62180    263
...      ...
74798    263
74799    263
74800    263
74801    263
74802    263

[1342 rows x 15 columns]
Punjab Cricket Association Stadium, Mohali
       mid        date                                       venue  \
124      2  2008-04-19  Punjab Cricket Association Stadium, Mohali
125      2  2008-04-19  Punjab Cricket Association Stadium, Mohali
126      2  2008-04-19  Punjab Cricket Association Stadium, Mohali
127      2  2008-04-19  Punjab Cricket Association Stadium, Mohali
128      2  2008-04-19  Punjab Cricket Association Stadium, Mohali
...    ...         ...                                         ...
61186  497  2015-05-16  Punjab Cricket Association Stadium, Mohali
61187  497  2015-05-16  Punjab Cricket Association Stadium, Mohali
61188  497  2015-05-16  Punjab Cricket Association Stadium, Mohali
61189  497  2015-05-16  Punjab Cricket Association Stadium, Mohali
61190  497  2015-05-16  Punjab Cricket Association Stadium, Mohali

                  bat_team            bowl_team       batsman   bowler  runs  \
124    Chennai Super Kings      Kings XI Punjab      PA Patel    B Lee     0
125    Chennai Super Kings      Kings XI Punjab      PA Patel    B Lee     0
126    Chennai Super Kings      Kings XI Punjab      PA Patel    B Lee     1
127    Chennai Super Kings      Kings XI Punjab     ML Hayden    B Lee     1
128    Chennai Super Kings      Kings XI Punjab     ML Hayden    B Lee     5
...                    ...                  ...           ...      ...   ...
61186      Kings XI Punjab  Chennai Super Kings  BE Hendricks  A Nehra   123
61187      Kings XI Punjab  Chennai Super Kings      R Dhawan  A Nehra   123
61188      Kings XI Punjab  Chennai Super Kings      R Dhawan  A Nehra   123
61189      Kings XI Punjab  Chennai Super Kings      R Dhawan  A Nehra   129
61190      Kings XI Punjab  Chennai Super Kings      R Dhawan  A Nehra   130

       wickets  overs  runs_last_5  wickets_last_5  striker  non-striker  \
124          0    0.1            0               0        0            0
125          0    0.2            0               0        0            0
126          0    0.3            1               0        1            0
127          0    0.4            1               0        1            0
128          0    0.5            5               0        4            1
...        ...    ...          ...             ...      ...          ...
61186        7   19.2           43               1       18            1
61187        7   19.3           42               1       18            1
61188        7   19.4           38               1       18            1
61189        7   19.5           43               1       24            1
61190        7   19.6           43               1       25            1

       total
124      263
125      263
126      263
127      263
128      263
...      ...
61186    263
61187    263
61188    263
61189    263
61190    263

[4247 rows x 15 columns]
Rajiv Gandhi International Stadium, Uppal
       mid        date                                      venue  \
733      7  2008-04-22  Rajiv Gandhi International Stadium, Uppal
734      7  2008-04-22  Rajiv Gandhi International Stadium, Uppal
735      7  2008-04-22  Rajiv Gandhi International Stadium, Uppal
736      7  2008-04-22  Rajiv Gandhi International Stadium, Uppal
737      7  2008-04-22  Rajiv Gandhi International Stadium, Uppal
...    ...         ...                                        ...
76009  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal
76010  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal
76011  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal
76012  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal
76013  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal

              bat_team               bowl_team          batsman        bowler  \
733    Deccan Chargers        Delhi Daredevils     AC Gilchrist    GD McGrath
734    Deccan Chargers        Delhi Daredevils     AC Gilchrist    GD McGrath
735    Deccan Chargers        Delhi Daredevils     AC Gilchrist    GD McGrath
736    Deccan Chargers        Delhi Daredevils  Y Venugopal Rao    GD McGrath
737    Deccan Chargers        Delhi Daredevils  Y Venugopal Rao    GD McGrath
...                ...                     ...              ...           ...
76009   Mumbai Indians  Rising Pune Supergiant        KH Pandya  DT Christian
76010   Mumbai Indians  Rising Pune Supergiant        KH Pandya  DT Christian
76011   Mumbai Indians  Rising Pune Supergiant        KH Pandya  DT Christian
76012   Mumbai Indians  Rising Pune Supergiant       MG Johnson  DT Christian
76013   Mumbai Indians  Rising Pune Supergiant        KH Pandya  DT Christian

       runs  wickets  overs  runs_last_5  wickets_last_5  striker  \
733       0        0    0.1            0               0        0
734       0        0    0.2            0               0        0
735       1        0    0.3            1               0        0
736       1        0    0.4            1               0        0
737       1        0    0.5            1               0        0
...     ...      ...    ...          ...             ...      ...
76009   121        7   19.2           40               0       40
76010   127        7   19.3           46               0       46
76011   128        7   19.4           47               0       47
76012   129        7   19.5           48               0       47
76013   129        8   19.6           47               1       47

       non-striker  total
733              0    263
734              0    263
735              0    263
736              0    263
737              0    263
...            ...    ...
76009           12    263
76010           12    263
76011           12    263
76012           13    263
76013           13    263

[5827 rows x 15 columns]
Sardar Patel Stadium, Motera
       mid        date                         venue          bat_team  \
14211  116  2010-03-15  Sardar Patel Stadium, Motera  Rajasthan Royals
14212  116  2010-03-15  Sardar Patel Stadium, Motera  Rajasthan Royals
14213  116  2010-03-15  Sardar Patel Stadium, Motera  Rajasthan Royals
14214  116  2010-03-15  Sardar Patel Stadium, Motera  Rajasthan Royals
14215  116  2010-03-15  Sardar Patel Stadium, Motera  Rajasthan Royals
...    ...         ...                           ...               ...
57964  470  2015-04-24  Sardar Patel Stadium, Motera  Rajasthan Royals
57965  470  2015-04-24  Sardar Patel Stadium, Motera  Rajasthan Royals
57966  470  2015-04-24  Sardar Patel Stadium, Motera  Rajasthan Royals
57967  470  2015-04-24  Sardar Patel Stadium, Motera  Rajasthan Royals
57968  470  2015-04-24  Sardar Patel Stadium, Motera  Rajasthan Royals

                         bowl_team      batsman       bowler  runs  wickets  \
14211             Delhi Daredevils  SA Asnodkar  MF Maharoof     4        0
14212             Delhi Daredevils  SA Asnodkar  MF Maharoof     5        0
14213             Delhi Daredevils     GC Smith  MF Maharoof     9        0
14214             Delhi Daredevils     GC Smith  MF Maharoof     9        0
14215             Delhi Daredevils     GC Smith  MF Maharoof     9        0
...                            ...          ...          ...   ...      ...
57964  Royal Challengers Bangalore     PV Tambe     MA Starc   127        9
57965  Royal Challengers Bangalore     PV Tambe     MA Starc   128        9
57966  Royal Challengers Bangalore    CH Morris     MA Starc   129        9
57967  Royal Challengers Bangalore     PV Tambe     MA Starc   129        9
57968  Royal Challengers Bangalore     PV Tambe     MA Starc   130        9

       overs  runs_last_5  wickets_last_5  striker  non-striker  total
14211    0.1            4               0        4            0    263
14212    0.2            5               0        5            0    263
14213    0.3            9               0        5            4    263
14214    0.4            9               0        5            4    263
14215    0.5            9               0        5            4    263
...      ...          ...             ...      ...          ...    ...
57964   19.2           32               4        2            0    263
57965   19.3           33               4        2            1    263
57966   19.4           34               4        3            1    263
57967   19.5           30               4        3            1    263
57968   19.6           30               4        3            2    263

[1484 rows x 15 columns]
Saurashtra Cricket Association Stadium
       mid        date                                   venue  \
62552  509  2016-04-14  Saurashtra Cricket Association Stadium
62553  509  2016-04-14  Saurashtra Cricket Association Stadium
62554  509  2016-04-14  Saurashtra Cricket Association Stadium
62555  509  2016-04-14  Saurashtra Cricket Association Stadium
62556  509  2016-04-14  Saurashtra Cricket Association Stadium
...    ...         ...                                     ...
73083  593  2017-04-29  Saurashtra Cricket Association Stadium
73084  593  2017-04-29  Saurashtra Cricket Association Stadium
73085  593  2017-04-29  Saurashtra Cricket Association Stadium
73086  593  2017-04-29  Saurashtra Cricket Association Stadium
73087  593  2017-04-29  Saurashtra Cricket Association Stadium

                      bat_team       bowl_team       batsman          bowler  \
62552  Rising Pune Supergiants   Gujarat Lions     AM Rahane         P Kumar
62553  Rising Pune Supergiants   Gujarat Lions     AM Rahane         P Kumar
62554  Rising Pune Supergiants   Gujarat Lions     AM Rahane         P Kumar
62555  Rising Pune Supergiants   Gujarat Lions  F du Plessis         P Kumar
62556  Rising Pune Supergiants   Gujarat Lions  F du Plessis         P Kumar
...                        ...             ...           ...             ...
73083            Gujarat Lions  Mumbai Indians  Basil Thampi  MJ McClenaghan
73084            Gujarat Lions  Mumbai Indians  Basil Thampi  MJ McClenaghan
73085            Gujarat Lions  Mumbai Indians    Ankit Soni  MJ McClenaghan
73086            Gujarat Lions  Mumbai Indians  Basil Thampi  MJ McClenaghan
73087            Gujarat Lions  Mumbai Indians    Ankit Soni  MJ McClenaghan

       runs  wickets  overs  runs_last_5  wickets_last_5  striker  \
62552     0        0    0.1            0               0        0
62553     4        0    0.2            4               0        4
62554     5        0    0.3            5               0        5
62555     5        0    0.4            5               0        5
62556     5        0    0.5            5               0        5
...     ...      ...    ...          ...             ...      ...
73083   144        9   19.2           46               3        0
73084   145        9   19.3           46               3        1
73085   146        9   19.4           46               3        1
73086   147        9   19.5           47               3        2
73087   153        9   19.6           53               3        7

       non-striker  total
62552            0    263
62553            0    263
62554            0    263
62555            0    263
62556            0    263
...            ...    ...
73083            0    263
73084            0    263
73085            1    263
73086            1    263
73087            2    263

[1229 rows x 15 columns]
Sawai Mansingh Stadium
       mid        date                   venue             bat_team  \
611      6  2008-04-21  Sawai Mansingh Stadium      Kings XI Punjab
612      6  2008-04-21  Sawai Mansingh Stadium      Kings XI Punjab
613      6  2008-04-21  Sawai Mansingh Stadium      Kings XI Punjab
614      6  2008-04-21  Sawai Mansingh Stadium      Kings XI Punjab
615      6  2008-04-21  Sawai Mansingh Stadium      Kings XI Punjab
...    ...         ...                     ...                  ...
46189  374  2013-05-12  Sawai Mansingh Stadium  Chennai Super Kings
46190  374  2013-05-12  Sawai Mansingh Stadium  Chennai Super Kings
46191  374  2013-05-12  Sawai Mansingh Stadium  Chennai Super Kings
46192  374  2013-05-12  Sawai Mansingh Stadium  Chennai Super Kings
46193  374  2013-05-12  Sawai Mansingh Stadium  Chennai Super Kings

              bowl_team    batsman       bowler  runs  wickets  overs  \
611    Rajasthan Royals     K Goel     MM Patel     0        0    0.1
612    Rajasthan Royals     K Goel     MM Patel     0        0    0.2
613    Rajasthan Royals     K Goel     MM Patel     0        0    0.3
614    Rajasthan Royals     K Goel     MM Patel     0        0    0.4
615    Rajasthan Royals     K Goel     MM Patel     1        0    0.5
...                 ...        ...          ...   ...      ...    ...
46189  Rajasthan Royals   DJ Bravo  JP Faulkner   133        4   19.2
46190  Rajasthan Royals   DJ Bravo  JP Faulkner   135        4   19.3
46191  Rajasthan Royals   DJ Bravo  JP Faulkner   136        4   19.4
46192  Rajasthan Royals  RA Jadeja  JP Faulkner   137        4   19.5
46193  Rajasthan Royals   DJ Bravo  JP Faulkner   141        4   19.6

       runs_last_5  wickets_last_5  striker  non-striker  total
611              0               0        0            0    263
612              0               0        0            0    263
613              0               0        0            0    263
614              0               0        0            0    263
615              1               0        1            0    263
...            ...             ...      ...          ...    ...
46189           36               1       16           11    263
46190           38               1       18           11    263
46191           37               1       19           11    263
46192           38               1       19           12    263
46193           41               1       23           12    263

[4110 rows x 15 columns]
Shaheed Veer Narayan Singh International Stadium
       mid        date                                             venue  \
43219  351  2013-04-28  Shaheed Veer Narayan Singh International Stadium
43220  351  2013-04-28  Shaheed Veer Narayan Singh International Stadium
43221  351  2013-04-28  Shaheed Veer Narayan Singh International Stadium
43222  351  2013-04-28  Shaheed Veer Narayan Singh International Stadium
43223  351  2013-04-28  Shaheed Veer Narayan Singh International Stadium
...    ...         ...                                               ...
68357  555  2016-05-22  Shaheed Veer Narayan Singh International Stadium
68358  555  2016-05-22  Shaheed Veer Narayan Singh International Stadium
68359  555  2016-05-22  Shaheed Veer Narayan Singh International Stadium
68360  555  2016-05-22  Shaheed Veer Narayan Singh International Stadium

[742 rows x 15 columns]
Sharjah Cricket Stadium
       mid        date                    venue             bat_team  \
48097  391  2014-04-17  Sharjah Cricket Stadium     Delhi Daredevils
48098  391  2014-04-17  Sharjah Cricket Stadium     Delhi Daredevils
48099  391  2014-04-17  Sharjah Cricket Stadium     Delhi Daredevils
48100  391  2014-04-17  Sharjah Cricket Stadium     Delhi Daredevils
48101  391  2014-04-17  Sharjah Cricket Stadium     Delhi Daredevils
...    ...         ...                      ...                  ...
50047  406  2014-04-27  Sharjah Cricket Stadium  Sunrisers Hyderabad
50048  406  2014-04-27  Sharjah Cricket Stadium  Sunrisers Hyderabad
50049  406  2014-04-27  Sharjah Cricket Stadium  Sunrisers Hyderabad
50050  406  2014-04-27  Sharjah Cricket Stadium  Sunrisers Hyderabad
50051  406  2014-04-27  Sharjah Cricket Stadium  Sunrisers Hyderabad

                         bowl_team     batsman     bowler  runs  wickets  \
48097  Royal Challengers Bangalore  MA Agarwal   MA Starc     0        0
48098  Royal Challengers Bangalore  MA Agarwal   MA Starc     1        0
48099  Royal Challengers Bangalore  MA Agarwal   MA Starc     3        0
48100  Royal Challengers Bangalore  MA Agarwal   MA Starc     3        0
48101  Royal Challengers Bangalore  MA Agarwal   MA Starc     4        0
...                            ...         ...        ...   ...      ...
50047          Chennai Super Kings   KV Sharma  MM Sharma   135        5
50048          Chennai Super Kings   DJG Sammy  MM Sharma   141        5
50049          Chennai Super Kings   DJG Sammy  MM Sharma   142        5
50050          Chennai Super Kings   KV Sharma  MM Sharma   143        5
50051          Chennai Super Kings   DJG Sammy  MM Sharma   145        5

       overs  runs_last_5  wickets_last_5  striker  non-striker  total
48097    0.1            0               0        0            0    263
48098    0.1            1               0        0            0    263
48099    0.2            3               0        2            0    263
48100    0.3            3               0        2            0    263
48101    0.4            4               0        3            0    263
...      ...          ...             ...      ...          ...    ...
50047   19.2           38               2       17           14    263
50048   19.3           43               2       20           17    263
50049   19.4           44               1       21           17    263
50050   19.5           44               1       21           17    263
50051   19.6           46               1       23           17    263

[744 rows x 15 columns]
Sheikh Zayed Stadium
       mid        date                 venue               bat_team  \
47973  390  2014-04-16  Sheikh Zayed Stadium  Kolkata Knight Riders
47974  390  2014-04-16  Sheikh Zayed Stadium  Kolkata Knight Riders
47975  390  2014-04-16  Sheikh Zayed Stadium  Kolkata Knight Riders
47976  390  2014-04-16  Sheikh Zayed Stadium  Kolkata Knight Riders
47977  390  2014-04-16  Sheikh Zayed Stadium  Kolkata Knight Riders
...    ...         ...                   ...                    ...
50291  408  2014-04-29  Sheikh Zayed Stadium       Rajasthan Royals
50292  408  2014-04-29  Sheikh Zayed Stadium       Rajasthan Royals
50293  408  2014-04-29  Sheikh Zayed Stadium       Rajasthan Royals
50294  408  2014-04-29  Sheikh Zayed Stadium       Rajasthan Royals
50295  408  2014-04-29  Sheikh Zayed Stadium       Rajasthan Royals

                   bowl_team      batsman         bowler  runs  wickets  \
47973         Mumbai Indians    G Gambhir         Z Khan     0        0
47974         Mumbai Indians    G Gambhir         Z Khan     0        0
47975         Mumbai Indians    G Gambhir         Z Khan     0        0
47976         Mumbai Indians    G Gambhir         Z Khan     0        0
47977         Mumbai Indians    G Gambhir         Z Khan     0        0
...                      ...          ...            ...   ...      ...
50291  Kolkata Knight Riders    SPD Smith  R Vinay Kumar   145        4
50292  Kolkata Knight Riders    AM Rahane  R Vinay Kumar   145        5
50293  Kolkata Knight Riders    SPD Smith  R Vinay Kumar   149        5
50294  Kolkata Knight Riders    SPD Smith  R Vinay Kumar   150        5
50295  Kolkata Knight Riders  JP Faulkner  R Vinay Kumar   152        5

       overs  runs_last_5  wickets_last_5  striker  non-striker  total
47973    0.1            0               0        0            0    263
47974    0.2            0               0        0            0    263
47975    0.3            0               0        0            0    263
47976    0.4            0               0        0            0    263
47977    0.5            0               0        0            0    263
...      ...          ...             ...      ...          ...    ...
50291   19.2           45               2       72           14    263
50292   19.3           44               3       72           14    263
50293   19.4           47               3       18            0    263
50294   19.5           48               3       19            0    263
50295   19.6           46               3       19            2    263

[836 rows x 15 columns]
St George's Park
       mid        date             venue             bat_team  \
7230    60  2009-04-20  St George's Park  Chennai Super Kings
7231    60  2009-04-20  St George's Park  Chennai Super Kings
7232    60  2009-04-20  St George's Park  Chennai Super Kings
7233    60  2009-04-20  St George's Park  Chennai Super Kings
7234    60  2009-04-20  St George's Park  Chennai Super Kings
...    ...         ...               ...                  ...
12075   98  2009-05-16  St George's Park       Mumbai Indians
12076   98  2009-05-16  St George's Park       Mumbai Indians
12077   98  2009-05-16  St George's Park       Mumbai Indians
12078   98  2009-05-16  St George's Park       Mumbai Indians
12079   98  2009-05-16  St George's Park       Mumbai Indians

                         bowl_team          batsman     bowler  runs  wickets  \
7230   Royal Challengers Bangalore         PA Patel    P Kumar     0        0
7231   Royal Challengers Bangalore         PA Patel    P Kumar     1        0
7232   Royal Challengers Bangalore        ML Hayden    P Kumar     4        0
7233   Royal Challengers Bangalore         PA Patel    P Kumar     4        0
7234   Royal Challengers Bangalore         PA Patel    P Kumar     5        0
...                            ...              ...        ...   ...      ...
12075          Chennai Super Kings        JP Duminy  JA Morkel   139        3
12076          Chennai Super Kings         AM Nayar  JA Morkel   139        4
12077          Chennai Super Kings         AM Nayar  JA Morkel   145        4
12078          Chennai Super Kings         AM Nayar  JA Morkel   146        4
12079          Chennai Super Kings  Harbhajan Singh  JA Morkel   147        5

       overs  runs_last_5  wickets_last_5  striker  non-striker  total
7230     0.1            0               0        0            0    263
7231     0.2            1               0        1            0    263
7232     0.3            4               0        3            1    263
7233     0.4            4               0        3            1    263
7234     0.5            5               0        3            1    263
...      ...          ...             ...      ...          ...    ...
12075   19.2           45               0       62           26    263
12076   19.3           44               1       62           26    263
12077   19.4           49               1       32            0    263
12078   19.5           50               1       33            0    263
12079   19.6           51               2       33            1    263

[870 rows x 15 columns]
Subrata Roy Sahara Stadium
       mid        date                       venue       bat_team  \
30383  247  2012-04-08  Subrata Roy Sahara Stadium  Pune Warriors
30384  247  2012-04-08  Subrata Roy Sahara Stadium  Pune Warriors
30385  247  2012-04-08  Subrata Roy Sahara Stadium  Pune Warriors
30386  247  2012-04-08  Subrata Roy Sahara Stadium  Pune Warriors
30387  247  2012-04-08  Subrata Roy Sahara Stadium  Pune Warriors
...    ...         ...                         ...            ...
47303  383  2013-05-19  Subrata Roy Sahara Stadium  Pune Warriors
47304  383  2013-05-19  Subrata Roy Sahara Stadium  Pune Warriors
47305  383  2013-05-19  Subrata Roy Sahara Stadium  Pune Warriors
47306  383  2013-05-19  Subrata Roy Sahara Stadium  Pune Warriors
47307  383  2013-05-19  Subrata Roy Sahara Stadium  Pune Warriors

              bowl_team     batsman   bowler  runs  wickets  overs  \
30383   Kings XI Punjab    JD Ryder  P Kumar     1        0    0.1
30384   Kings XI Punjab  SC Ganguly  P Kumar     5        0    0.2
30385   Kings XI Punjab  SC Ganguly  P Kumar     5        0    0.3
30386   Kings XI Punjab  SC Ganguly  P Kumar     5        0    0.4
30387   Kings XI Punjab  SC Ganguly  P Kumar     9        0    0.5
...                 ...         ...      ...   ...      ...    ...
47303  Delhi Daredevils   LJ Wright   S Kaul   166        4   19.2
47304  Delhi Daredevils  AD Mathews   S Kaul   167        4   19.3
47305  Delhi Daredevils   LJ Wright   S Kaul   167        5   19.4
47306  Delhi Daredevils  AD Mathews   S Kaul   168        5   19.5
47307  Delhi Daredevils    RV Gomez   S Kaul   172        5   19.6

       runs_last_5  wickets_last_5  striker  non-striker  total
30383            1               0        1            0    263
30384            5               0        4            1    263
30385            5               0        4            1    263
30386            5               0        4            1    263
30387            9               0        8            1    263
...            ...             ...      ...          ...    ...
47303           62               0       44           28    263
47304           62               0       44           29    263
47305           61               1       44           29    263
47306           61               1       30            0    263
47307           59               1       30            4    263

[2086 rows x 15 columns]
SuperSport Park
       mid        date            venue          bat_team         bowl_team  \
8475    70  2009-04-28  SuperSport Park  Delhi Daredevils  Rajasthan Royals
8476    70  2009-04-28  SuperSport Park  Delhi Daredevils  Rajasthan Royals
8477    70  2009-04-28  SuperSport Park  Delhi Daredevils  Rajasthan Royals
8478    70  2009-04-28  SuperSport Park  Delhi Daredevils  Rajasthan Royals
8479    70  2009-04-28  SuperSport Park  Delhi Daredevils  Rajasthan Royals
...    ...         ...              ...               ...               ...
13323  108  2009-05-22  SuperSport Park  Delhi Daredevils   Deccan Chargers
13324  108  2009-05-22  SuperSport Park  Delhi Daredevils   Deccan Chargers
13325  108  2009-05-22  SuperSport Park  Delhi Daredevils   Deccan Chargers
13326  108  2009-05-22  SuperSport Park  Delhi Daredevils   Deccan Chargers
13327  108  2009-05-22  SuperSport Park  Delhi Daredevils   Deccan Chargers

          batsman          bowler  runs  wickets  overs  runs_last_5  \
8475    G Gambhir  AD Mascarenhas     0        0    0.1            0
8476    G Gambhir  AD Mascarenhas     1        0    0.2            1
8477     V Sehwag  AD Mascarenhas     7        0    0.3            7
8478     V Sehwag  AD Mascarenhas     7        0    0.4            7
8479     V Sehwag  AD Mascarenhas     7        0    0.5            7
...           ...             ...   ...      ...    ...          ...
13323    R Bhatia        RP Singh   151        5   19.2           43
13324    R Bhatia        RP Singh   151        6   19.3           42
13325    A Mishra        RP Singh   152        6   19.4           42
13326  TM Dilshan        RP Singh   153        7   19.5           42
13327  PJ Sangwan        RP Singh   153        8   19.6           41

       wickets_last_5  striker  non-striker  total
8475                0        0            0    263
8476                0        1            0    263
8477                0        6            1    263
8478                0        6            1    263
8479                0        6            1    263
...               ...      ...          ...    ...
13323               2       64            4    263
13324               3       64            4    263
13325               3       64            0    263
13326               4       65            0    263
13327               5        0            0    263

[1377 rows x 15 columns]
Vidarbha Cricket Association Stadium, Jamtha
       mid        date                                         venue  \
17961  146  2010-04-05  Vidarbha Cricket Association Stadium, Jamtha
17962  146  2010-04-05  Vidarbha Cricket Association Stadium, Jamtha
17963  146  2010-04-05  Vidarbha Cricket Association Stadium, Jamtha
17964  146  2010-04-05  Vidarbha Cricket Association Stadium, Jamtha
17965  146  2010-04-05  Vidarbha Cricket Association Stadium, Jamtha
...    ...         ...                                           ...
19337  156  2010-04-12  Vidarbha Cricket Association Stadium, Jamtha
19338  156  2010-04-12  Vidarbha Cricket Association Stadium, Jamtha
19339  156  2010-04-12  Vidarbha Cricket Association Stadium, Jamtha
19340  156  2010-04-12  Vidarbha Cricket Association Stadium, Jamtha
19341  156  2010-04-12  Vidarbha Cricket Association Stadium, Jamtha

               bat_team                    bowl_team    batsman     bowler  \
17961  Rajasthan Royals              Deccan Chargers    MJ Lumb  RJ Harris
17962  Rajasthan Royals              Deccan Chargers    MJ Lumb  RJ Harris
17963  Rajasthan Royals              Deccan Chargers    MJ Lumb  RJ Harris
17964  Rajasthan Royals              Deccan Chargers    MJ Lumb  RJ Harris
17965  Rajasthan Royals              Deccan Chargers    MJ Lumb  RJ Harris
...                 ...                          ...        ...        ...
19337   Deccan Chargers  Royal Challengers Bangalore  RJ Harris  JH Kallis
19338   Deccan Chargers  Royal Challengers Bangalore  RJ Harris  JH Kallis
19339   Deccan Chargers  Royal Challengers Bangalore  RJ Harris  JH Kallis
19340   Deccan Chargers  Royal Challengers Bangalore  RJ Harris  JH Kallis
19341   Deccan Chargers  Royal Challengers Bangalore  RJ Harris  JH Kallis

       runs  wickets  overs  runs_last_5  wickets_last_5  striker  \
17961     0        0    0.1            0               0        0
17962     0        0    0.2            0               0        0
17963     0        0    0.3            0               0        0
17964     0        0    0.4            0               0        0
17965     0        0    0.5            0               0        0
...     ...      ...    ...          ...             ...      ...
19337   144        6   19.2           38               2        6
19338   150        6   19.3           43               2       12
19339   150        6   19.4           39               2       12
19340   150        6   19.5           38               2       12
19341   151        6   19.6           38               2       13

       non-striker  total
17961            0    263
17962            0    263
17963            0    263
17964            0    263
17965            0    263
...            ...    ...
19337            6    263
19338            6    263
19339            6    263
19340            6    263
19341            6    263

[370 rows x 15 columns]
Wankhede Stadium
       mid        date             venue                bat_team  \
370      4  2008-04-20  Wankhede Stadium          Mumbai Indians
371      4  2008-04-20  Wankhede Stadium          Mumbai Indians
372      4  2008-04-20  Wankhede Stadium          Mumbai Indians
373      4  2008-04-20  Wankhede Stadium          Mumbai Indians
374      4  2008-04-20  Wankhede Stadium          Mumbai Indians
...    ...         ...               ...                     ...
75768  615  2017-05-16  Wankhede Stadium  Rising Pune Supergiant
75769  615  2017-05-16  Wankhede Stadium  Rising Pune Supergiant
75770  615  2017-05-16  Wankhede Stadium  Rising Pune Supergiant
75771  615  2017-05-16  Wankhede Stadium  Rising Pune Supergiant
75772  615  2017-05-16  Wankhede Stadium  Rising Pune Supergiant

                         bowl_team   batsman     bowler  runs  wickets  overs  \
370    Royal Challengers Bangalore  L Ronchi    P Kumar     0        0    0.1
371    Royal Challengers Bangalore  L Ronchi    P Kumar     4        0    0.2
372    Royal Challengers Bangalore  L Ronchi    P Kumar     4        0    0.3
373    Royal Challengers Bangalore  L Ronchi    P Kumar     4        0    0.4
374    Royal Challengers Bangalore  L Ronchi    P Kumar     8        0    0.5
...                            ...       ...        ...   ...      ...    ...
75768               Mumbai Indians  MS Dhoni  JJ Bumrah   154        3   19.2
75769               Mumbai Indians  MS Dhoni  JJ Bumrah   156        3   19.3
75770               Mumbai Indians  MS Dhoni  JJ Bumrah   162        3   19.4
75771               Mumbai Indians  MS Dhoni  JJ Bumrah   162        3   19.5
75772               Mumbai Indians  MS Dhoni  JJ Bumrah   162        4   19.6

       runs_last_5  wickets_last_5  striker  non-striker  total
370              0               0        0            0    263
371              4               0        4            0    263
372              4               0        4            0    263
373              4               0        4            0    263
374              8               0        8            0    263
...            ...             ...      ...          ...    ...
75768           50               0       58           32    263
75769           51               0       58           34    263
75770           57               0       58           40    263
75771           56               0       58           40    263
75772           56               1       58           40    263

[7048 rows x 15 columns]

In [63]:
dypatil= df2.get_group('Dr DY Patil Sports Academy')

In [68]:
df_yuvraj = df[df.batsman == 'Yuvraj Singh'].reset_index()

In [58]:
df_yuvraj

,index,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,657,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,68,3,7.4,52,3,15,4,166
1,658,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,69,3,7.4,53,3,15,4,166
2,659,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,70,3,7.5,50,3,15,4,166
3,660,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,SK Warne,71,3,8.6,51,3,15,5,166
4,663,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,SK Warne,73,3,8.3,49,3,16,6,166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,73681,598,2017-05-02,Feroz Shah Kotla,Sunrisers Hyderabad,Delhi Daredevils,Yuvraj Singh,K Rabada,171,3,19.1,59,0,57,24,185
976,73682,598,2017-05-02,Feroz Shah Kotla,Sunrisers Hyderabad,Delhi Daredevils,Yuvraj Singh,K Rabada,175,3,19.2,63,0,61,24,185
977,73683,598,2017-05-02,Feroz Shah Kotla,Sunrisers Hyderabad,Delhi Daredevils,Yuvraj Singh,K Rabada,176,3,19.3,63,0,62,24,185
978,73685,598,2017-05-02,Feroz Shah Kotla,Sunrisers Hyderabad,Delhi Daredevils,Yuvraj Singh,K Rabada,181,3,19.5,66,0,66,25,185
979,73686,598,2017-05-02,Feroz Shah Kotla,Sunrisers Hyderabad,Delhi Daredevils,Yuvraj Singh,K Rabada,185,3,19.6,69,0,70,25,185

In [60]:
df_yuvraj.columns

Index(['index', 'mid', 'date', 'venue', 'bat_team', 'bowl_team', 'batsman',
       'bowler', 'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5',
       'striker', 'non-striker', 'total'],
      dtype='object')

In [61]:
df_yuvraj.shape

(980, 16)

In [62]:
df['batsman'].unique()

array(['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey',
       'Mohammad Hafeez', 'PA Patel', 'ML Hayden', 'MEK Hussey',
       'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'T Kohli',
       'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja',
       'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'L Ronchi',
       'ST Jayasuriya', 'DJ Thornely', 'RV Uthappa', 'PR Shah',
       'AM Nayar', 'SM Pollock', 'Harbhajan Singh', 'AC Gilchrist',
       'Y Venugopal Rao', 'VVS Laxman', 'A Symonds', 'RG Sharma',
       'SB Styris', 'AS Yadav', 'SB Bangar', 'WPUJC Vaas', 'RP Singh',
       'K Goel', 'JR Hopes', 'KC Sangakkara', 'DPMD Jayawardene',
       'Yuvraj Singh', 'IK Pathan', 'S Sohal', 'B Lee', 'PP Chawla',
       'WA Mota', 'Shahid Afridi', 'RR Sarwan', 'S Sreesanth',
       'VRV Singh', 'S Chanderpaul', 'R Dravid', 'LRPL Taylor',
       'JH Kallis', 'V Kohli', 'MV Boucher', 'P Kumar', 'SB Joshi',
       'Z Khan', 'R Vinay Kumar', 'WP Saha', 'LR Shukla', 'AB Agarkar',
       'M Kartik', 'I Sharma', 'AM Rahane', 'DJ Bravo', 'MA Khote',
       'G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib Malik', 'MK Tiwary',
       'KD Karthik', 'R Bhatia', 'MF Maharoof', 'VY Mahesh', 'DB Das',
       'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna', 'GC Smith',
       'SA Asnodkar', 'Sohail Tanvir', 'SP Fleming', 'S Vidyut',
       'JA Morkel', 'LPC Silva', 'DB Ravi Teja', 'SE Marsh',
       'YV Takawale', 'SS Tiwary', 'RR Raje', 'Joginder Sharma',
       'MS Gony', 'M Muralitharan', 'M Ntini', 'W Jaffer', 'CL White',
       'Misbah-ul-Haq', 'DT Patil', 'A Kumble', 'DW Steyn', 'S Anirudha',
       'MM Patel', 'AB de Villiers', 'A Chopra', 'BJ Hodge', 'T Taibu',
       'Umar Gul', 'PP Ojha', 'SP Goswami', 'B Akhil', 'Salman Butt',
       'TM Dilshan', 'A Mishra', 'J Arunkumar', 'Iqbal Abdulla',
       'CK Kapugedera', 'LA Pomersbach', 'Shoaib Akhtar', 'AB Dinda',
       'SR Tendulkar', 'B Chipli', 'DR Smith', 'SD Chitnis',
       'Kamran Akmal', 'TM Srivastava', 'MK Pandey', 'RR Powar',
       'JP Duminy', 'JD Ryder', 'KP Pietersen', 'CH Gayle',
       'MC Henriques', 'A Flintoff', 'FH Edwards', 'PC Valthaty',
       'RJ Quiney', 'AD Mascarenhas', 'AS Raut', 'Pankaj Singh',
       'RS Bopara', 'DL Vettori', 'M Manhas', 'PJ Sangwan', 'MN van Wyk',
       'AA Bilakhia', 'TL Suman', 'Shoaib Ahmed', 'GR Napier',
       'R Bishnoi', 'RE van der Merwe', 'KP Appanna', 'M Vijay',
       'SB Jakati', 'L Balaji', 'NV Ojha', 'LA Carseldine', 'RJ Harris',
       'D du Preez', 'DS Kulkarni', 'SM Harwood', 'Yashpal Singh',
       'AN Ghosh', 'AD Mathews', 'SM Katich', 'DA Warner', 'J Botha',
       'A Nehra', 'Mashrafe Mortaza', 'GJ Bailey', 'AB McDonald',
       'Y Nagar', 'Niraj Patel', 'T Henderson', 'A Singh', 'R Ashwin',
       'T Thushara', 'Mohammad Ashraful', 'CA Pujara', 'OA Shah',
       'AP Tare', 'AT Rayudu', 'R Sathish', 'R McLaren', 'MS Bisla',
       'YA Abdulla', 'EJG Morgan', 'AA Jhunjhunwala', 'P Dogra',
       'A Uniyal', 'KA Pollard', 'MJ Lumb', 'DR Martyn', 'S Narwal',
       'M Morkel', 'Anirudh Singh', 'Jaskaran Singh', 'FY Fazal',
       'AC Voges', 'MD Mishra', 'J Theron', 'R Sharma', 'Mandeep Singh',
       'KM Jadhav', 'SW Tait', 'PD Collingwood', 'VS Malik',
       'SJ Srivastava', 'AP Dole', 'Bipul Sharma', 'DE Bollinger',
       'BAW Mendis', 'B Sumanth', 'C Madan', 'AG Paunikar', 'AJ Finch',
       'MR Marsh', 'STR Binny', 'IR Jaggi', 'DT Christian', 'RV Gomez',
       'UBT Chand', 'UT Yadav', 'Sunny Singh', 'NJ Rimmington',
       'MA Agarwal', 'AUK Pathan', 'AL Menaria', 'DJ Jacobs',
       'WD Parnell', 'TD Paine', 'SB Wagh', 'AC Thomas', 'BJ Haddin',
       'NLTC Perera', 'MS Wade', 'JE Taylor', 'RN ten Doeschate',
       'SL Malinga', 'AG Murtaza', 'TR Birt', 'Harpreet Singh',
       'NL McCullum', 'DH Yagnik', 'AC Blizzard', 'M Klinger',
       'I Malhotra', 'A Mithun', 'P Parameswaran', 'AA Chavan',
       'ND Doshi', 'CJ Ferguson', 'B Kumar', 'S Rana', 'JEC Franklin',
       'Shakib Al Hasan', 'F du Plessis', 'SPD Smith', 'MN Samuels',
       'KK Cooper', 'HV Patel', 'Ankit Sharma', 'RE Levi', 'RR Bhatkal',
       'Harmeet Singh', 'BA Bhatt', 'CJ McKay', 'DJ Harris', 'N Saini',
       'DA Miller', 'Azhar Mahmood', 'A Ashish Reddy', 'V Pratap Singh',
       'BB Samantray', 'RJ Peterson', 'S Nadeem', 'VR Aaron', 'MJ Clarke',
       'AP Majumdar', 'Gurkeerat Singh', 'P Awana', 'SP Narine',
       'A Chandila', 'PA Reddy', 'MC Juneja', 'AD Russell', 'KK Nair',
       'KB Arun Karthik', 'GH Vihari', 'MDKJ Perera', 'R Shukla',
       'JD Unadkat', 'M Vohra', 'JP Faulkner', 'R Rampaul', 'BJ Rohrer',
       'Q de Kock', 'KV Sharma', 'SMSM Senanayake', 'LJ Wright',
       'X Thalaivan Sargunam', 'DJG Sammy', 'MG Johnson', 'A Mukund',
       'SV Samson', 'BMAJ Mendis', 'KL Rahul', 'CM Gautam',
       'KW Richardson', 'Parvez Rasool', 'GJ Maxwell', 'R Dhawan',
       'SA Yadav', 'CJ Anderson', 'JJ Bumrah', 'CA Lynn', 'MA Starc',
       'AR Patel', 'Sandeep Sharma', 'BR Dunk', 'Shivam Sharma',
       'LMP Simmons', 'VH Zol', 'BCJ Cutting', 'Mohammed Shami',
       'BE Hendricks', 'S Gopal', 'M de Lange', 'RR Rossouw', 'JO Holder',
       'JDS Neesham', 'Imran Tahir', 'MM Sharma', 'DJ Hooda', 'CH Morris',
       'SS Iyer', 'SA Abbott', 'AN Ahmed', 'YS Chahal', 'J Suchith',
       'P Negi', 'RG More', 'Anureet Singh', 'HH Pandya',
       'NM Coulter-Nile', 'PV Tambe', 'MJ McClenaghan', 'DJ Muthuswami',
       'SN Thakur', 'SN Khan', 'D Wiese', 'S Aravind', 'JC Buttler',
       'CR Brathwaite', 'MP Stoinis', 'C Munro', 'P Sahu', 'KH Pandya',
       'TG Southee', 'MJ Guptill', 'KJ Abbott', 'TM Head', 'AD Nath',
       'NS Naik', 'Ishan Kishan', 'SW Billings', 'RR Pant',
       'KS Williamson', 'KC Cariappa', 'PSP Handscomb', 'Sachin Baby',
       'J Yadav', 'UT Khawaja', 'HM Amla', 'BB Sran', 'N Rana',
       'F Behardien', 'ER Dwivedi', 'JJ Roy', 'BA Stokes', 'Vishnu Vinod',
       'TS Mills', 'Basil Thampi', 'CR Woakes', 'V Shankar',
       'Rashid Khan', 'RA Tripathi', 'RD Chahar', 'LH Ferguson',
       'C de Grandhomme', 'PJ Cummins', 'Mohammad Nabi', 'Kuldeep Yadav',
       'Washington Sundar', 'S Badree', 'A Choudhary', 'AR Bawne',
       'AJ Tye', 'Ankit Soni', 'K Rabada', 'AF Milne', 'SP Jackson',
       'Swapnil Singh', 'R Tewatia', 'AS Rajpoot'], dtype=object)

In [70]:
df_ganguly = df[df['batsman'] == "SC Ganguly"]

In [73]:
df_yuv_gan = pd.concat([df_yuvraj,df_ganguly],axis=1)

In [74]:
df_yuv_gan

,index,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,...,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,657.0,6.0,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,68.0,3.0,...,SC Ganguly,P Kumar,1.0,0.0,0.1,1.0,0.0,0.0,0.0,263.0
1,658.0,6.0,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,69.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,659.0,6.0,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,70.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,660.0,6.0,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,SK Warne,71.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,663.0,6.0,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,SK Warne,73.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SC Ganguly,SR Watson,24.0,0.0,4.3,24.0,0.0,12.0,8.0,263.0
35711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SC Ganguly,SR Watson,26.0,0.0,4.5,26.0,0.0,13.0,9.0,263.0
35713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SC Ganguly,SW Tait,28.0,0.0,5.1,26.0,0.0,13.0,11.0,263.0
35714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SC Ganguly,SW Tait,29.0,0.0,5.2,27.0,0.0,14.0,11.0,263.0
35716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SC Ganguly,SW Tait,30.0,1.0,5.4,26.0,1.0,14.0,11.0,263.0

In [76]:
df_yuv_gan.to_csv("C:\Anil\Projects\DS Training\player.csv")

In [78]:
df_yuv_gan

,index,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,657.0,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,68,3,7.4,52,3,15,4,166
1,658.0,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,69,3,7.4,53,3,15,4,166
2,659.0,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,D Salunkhe,70,3,7.5,50,3,15,4,166
3,660.0,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,SK Warne,71,3,8.6,51,3,15,5,166
4,663.0,6,2008-04-21,Sawai Mansingh Stadium,Kings XI Punjab,Rajasthan Royals,Yuvraj Singh,SK Warne,73,3,8.3,49,3,16,6,166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35709,NaN,290,2012-05-08,Subrata Roy Sahara Stadium,Pune Warriors,Rajasthan Royals,SC Ganguly,SR Watson,24,0,4.3,24,0,12,8,125
35711,NaN,290,2012-05-08,Subrata Roy Sahara Stadium,Pune Warriors,Rajasthan Royals,SC Ganguly,SR Watson,26,0,4.5,26,0,13,9,125
35713,NaN,290,2012-05-08,Subrata Roy Sahara Stadium,Pune Warriors,Rajasthan Royals,SC Ganguly,SW Tait,28,0,5.1,26,0,13,11,125
35714,NaN,290,2012-05-08,Subrata Roy Sahara Stadium,Pune Warriors,Rajasthan Royals,SC Ganguly,SW Tait,29,0,5.2,27,0,14,11,125
35716,NaN,290,2012-05-08,Subrata Roy Sahara Stadium,Pune Warriors,Rajasthan Royals,SC Ganguly,SW Tait,30,1,5.4,26,1,14,11,125

df_yuv_gan

In [79]:
df = pd.DataFrame([10,20,30],index=[3,1,2])

In [80]:
df

    0
3  10
1  20
2  30

In [81]:
df[0:1]

    0
3  10

In [83]:
df.loc[3]   #this works on index

0    10
Name: 3, dtype: int64

In [84]:
df.iloc[0]   #This works on row Number

0    10
Name: 3, dtype: int64

In [98]:
#List Assignment
#https://www.codesdope.com/practice/python-make-a-list/